### ISSUE TITLE
like.co/in UI issue

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#1305]
- [x] 1) "Reinventing the Like, open with app" 中文 text: 化讚為賞，盡在指掌

- [ ] 2) "The Overview" tab bar should be hidden as there is only one page now

![image](https://user-images.githubusercontent.com/17264698/69857029-ee106600-12c9-11ea-8474-cc2e02372412.png)

**Comment by edmondyu** [comment]
and both tabs will be shown occasionally, not sure about the pattern.

![image](https://user-images.githubusercontent.com/17264698/69865571-70098a80-12dc-11ea-85b2-39071b74a562.png)

**Comment by williamchong007** [comment]
point 1 should be fixed in
https://github.com/likecoin/likecoin-store/commit/7f4a6c9afbbad23a7adba6cf45459a27aeff112a
