### ISSUE TITLE
Login by MetaMask flow issue

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#1307]
rinkeby account: 0x795e65AD28e08721898C4D94b1a521c072c168d2

- 去到最後一個 step，㩒 ok 掣冇反應。
- 冇入何㩒得嘅地方走，唯有 back 番出去，返回主頁面 refresh 重新用 MetaMask 再 login 過，會重複再跑一次，入完密碼後，出第二個error 畫面，error message "contact is already taken"
- 嘗試用剛剛入完密碼果個 account (brendagimiu@gmail.com) oauth 登入，出第三個 error 畫面，error message "The contact has been used in the system but not linked by social platform"

![MetaMask login case issue](https://user-images.githubusercontent.com/17264698/69861703-dccc5700-12d3-11ea-8d83-335cfcd95f8c.png)

![image](https://user-images.githubusercontent.com/17264698/69862023-8ad80100-12d4-11ea-8a58-0726c1f05063.png)

![image](https://user-images.githubusercontent.com/17264698/69862307-1782bf00-12d5-11ea-95ab-d35a58c9f297.png)

**Comment by williamchong007** [comment]
你入完密碼嘅 authcore ac 係你未 login bind oauth 之前係淨係可以用 password login，唔係 bug
OK 制冇反應睇緊

**Comment by edmondyu** [comment]
但係我用 email pwd login, 又出以下嘅註冊 Liker ID 畫面；咁我當新註冊啦，佢又出「此電郵地址已被註冊」，叫我用番電子錢包登入
![image](https://user-images.githubusercontent.com/17264698/69865825-4d2ba600-12dd-11ea-8bc3-278cd53c6010.png)

**Comment by williamchong007** [comment]
should be fixed in https://github.com/likecoin/likecoin-store/pull/1312
contact used issue is due to user did actually register successfully with the email
