### ISSUE TITLE
`USE_AUTHCORE_LOGIN` should be more human readable when login by MetaMask

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#1311]
用這 address 0xF97FCC6B0aD72d3ADe4f588aC07304AA43efEF5D 嘗試登入，sign 完出下面個 error screen:

![image](https://user-images.githubusercontent.com/17264698/69868523-e7431c80-12e4-11ea-9012-d272523f09aa.png)

**Comment by williamchong007** [comment]
the actual error `USE_AUTHCORE_LOGIN`, should be more descriptive to tell user to login via authcore

**Comment by nwingt** [comment]
I think this has been patched in 108f81e, please check again

**Comment by williamchong007** [comment]
the problem is this message is still confusing
trying to improve it in https://github.com/likecoin/likecoin-store/issues/1311

**Comment by williamchong007** [comment]
Should be improved in https://github.com/likecoin/likecoin-store/pull/1327
