### ISSUE TITLE
LikeCoin button login: Authcore 登入畫面被裁掉右邊

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#1314]
點 LikeCoin button 後login。無法縮小也無法向左捽。見圖。

iPhone 6s, Safari, iOS 12.4.1

![IMG_2095](https://user-images.githubusercontent.com/17264698/70099770-c70bb880-166a-11ea-9817-0e48d4c5c4db.PNG)

**Comment by nwingt** [comment]
Can’t repeat on iPhone X iOS 13.2.3
