### ISSUE TITLE
phone registration issue

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#1332]
Failed to register by phone number.  Reported area: TW and US

![image](https://user-images.githubusercontent.com/17264698/70892063-63e33400-2023-11ea-9f71-a9bf1aea763c.png)

**Comment by ckxpress** [comment]
filed an issue on Authcore gitlab last week - https://gitlab.com/blocksq/authcore-js/issues/56

**Comment by williamchong007** [comment]
should be fixed in authcore side
