### ISSUE TITLE
Login via metamask button should be more subtle

### ISSUE THREAD

**Issue by williamchong007** [likecoin/likecoin-store#1363]
Login via metamask option is only for legacy metamask users to migrate to our new auth system. Currently it has a bright orange color, which makes it stands out too much in the UI. We want it to be less subtle, especially to new users

Expected: Make it less colorful/attractive, such that new users won't be clicking that button wrongly.

**Comment by nwingt** [comment]
Revert back to original design then

**Comment by williamchong007** [comment]
I remember the issue was users all thinking it's the title for dialog but not a button. Maybe not completely revert to original, but something less shinny will do

**Comment by nwingt** [comment]
Closed in #1365
