### ISSUE TITLE
Translation issue? (TC/SC)

### ISSUE THREAD

**Issue by Aludirk** [likecoin/likecoin-store#208]
like.co 需宜用支援以太坊加密貨幣錢包 MetaMask 的瀏覽器。

需宜用？
係 `需要用` 定係 `適宜用`

**Comment by williamchong007** [comment]
![image](https://user-images.githubusercontent.com/6198816/38719483-de4a8928-3f24-11e8-905b-71668771a9b9.png)
missing SC translate

`Registering with the following user info:`
