### ISSUE TITLE
email verification window text offset in ES locale

### ISSUE THREAD

**Issue by williamchong007** [likecoin/likecoin-store#210]
![image](https://user-images.githubusercontent.com/6198816/38719371-33234ef4-3f24-11e8-8c25-e441c908b9dd.png)

**Comment by nnkken** [comment]
This issue also appears in Trust on Android

**Comment by williamchong007** [comment]
![image](https://user-images.githubusercontent.com/6198816/38719559-36f54f90-3f25-11e8-8e0f-f6d8197e3df4.png)
button seems large

**Comment by nwingt** [comment]
French also

![image](https://user-images.githubusercontent.com/17264716/38720551-364b9fb4-3f29-11e8-91e0-b2b72a27087c.png)
