### ISSUE TITLE
Should not pop-up metamask screen in trust browser

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#219]
Although that does not affect the successful registration process.  The metamask popup will now being displayed during the "sign" step, at the background; and will disappear upon successful registration.

**Comment by williamchong007** [comment]
唔明，有無圖？

**Comment by edmondyu** [comment]
![img_0225](https://user-images.githubusercontent.com/17264698/38720899-8975e900-3f2a-11e8-9962-97b39349823c.PNG)

**Comment by williamchong007** [comment]
@joshkiu expect 係完全冇嘢，定係收埋個狐狸頭？

**Comment by joshkiu** [comment]
let's do it with Mobile/Trust optimization next week

**Comment by nwingt** [comment]
Should be fixed in #280 and #281
