### ISSUE TITLE
Wrong Japanese and Korean translation in token sale page

### ISSUE THREAD

**Issue by nnkken** [likecoin/likecoin-store#230]
Japanese: `身分確認を行って10米ドル以上購入してください`
(Google translate: `To acquire more than 10 ETH, your identity must be confirmed`)

Korean: `미화 10을/를 넘는 금액을 구매하려면 ID를 인증해 주십시오`
(Google translate: `Please verify your ID if you want to purchase over $ / USD`)

English: `Verifiy your identity and to purchase more than 10 ETH`

**Comment by simonbut** [comment]
fix on c25bd3256fd32078bb803248e997f3aa0529f8e3
