### ISSUE TITLE
Peer-2-peer transfer failed

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-store#241]
location: like.co/[id]
platform: iOS trust

Confirm button cannot be pressed, just no response.

**Comment by williamchong007** [comment]
![screenshot_2018-04-13-17-09-28](https://user-images.githubusercontent.com/6198816/38726748-abb92730-3f3d-11e8-8ea0-8b15da779ae5.png)
@edmondyu 無見到 not supported 嘅字樣？

**Comment by nwingt** [comment]
Fixed by fixing disabled button style
