### ISSUE TITLE
Please add the following message in mission card "complete token sale"

### ISSUE THREAD

**Issue by simonbut** [likecoin/likecoin-store#405]
Please note that if you buy LikeCoin through MyEthShop or TideBit, you can't complete the Token Sale Task on like.co as you are not buy it on like.co. As a result, You can't get any LikeCoin bonus.

不過，經過 MyEthShop 或 TideBit 參與代幣發行的話，會完成不了 like.co 的代幣發售任務，得不到額外的 LikeCoin 獎勵。

**Comment by simonbut** [comment]
please change into these message:

Please note that if you buy LikeCoin through the third party like MyEthShop, you can't complete the Token Sale Task on like.co as you are not buy it on like.co. As a result, You can't get any LikeCoin bonus.

不過，經過第三方渠道如 MyEthShop 參與代幣發行的話，會完成不了 like.co 的代幣發售任務，得不到額外的 LikeCoin 獎勵。

**Comment by williamchong007** [comment]
amended to `Note: If you join the token sale through third parties, e.g. MyEthShop, this mission will not be completed. As a result, you will not get bonus for this mission.`
